apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvna
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvna
  template:
    metadata:
      labels:
        app: dvna
    spec:
      containers:
      - name: dvna
        image: btthanhk4/dvna:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: dvna-svc
  namespace: default
spec:
  selector:
    app: dvna
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
