FROM node:14-bullseye

WORKDIR /app

COPY . .

RUN npm install

COPY wait-for-it.sh /app/wait-for-it.sh
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/wait-for-it.sh /app/entrypoint.sh

EXPOSE 9090

CMD ["/app/entrypoint.sh"]
