apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvna
  labels:
    app: dvna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvna
  template:
    metadata:
      labels:
        app: dvna
    spec:
      containers:
        - name: dvna
          image: btthanhk4/dvna:latest
          ports:
            - containerPort: 9090
          env:
            - name: MYSQL_DATABASE
              value: dvna
            - name: MYSQL_USER
              value: dvnauser
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_HOST
              value: "192.168.61.101"
            - name: MYSQL_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: dvna-svc
spec:
  type: NodePort
  selector:
    app: dvna
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32090
